### ISSUE TITLE
Python Runtime Deadlocks When A Large Amount Of Data Is Returned

### ISSUE THREAD

**Issue by annalore** [kubeless/runtimes#48]
When a function tries to put an amount of data larger than the Pipe is capable of handling (potentially 16k or 64k), onto the queue for return to the main process, the function deadlocks until the timeout value is reached.

**Comment by meseta** [comment]
We also encountered this, and are going to build a custom runtime that chunks up the return into less than 64kb:

Putting return value inside `funcWrap()`
```python
def funcWrap(q, event, c):
    try:
        retval = func(event, c)
    except Exception as inst:
        retval = inst

    # chunk up return value to fit inside OS pipe max 64kb
    buff = io.BytesIO(pickle.dumps(ret))

    while True: # loop through and read chunks
        chunk = buff.read(pipe_chunk_size)
        if len(chunk) == 0;
            break
        q.put(chunk)

    q.put()
```

Reassembling return value:
```python
                acc = b""
                while not q.empty(): # reassemble return value
                    acc += q.get()

                res = pickle.loads(acc)

                if isinstance(res, Exception):
                    raise res

                return res
```

Source:
https://github.com/HummingbirdTechGroup/runtimes/blob/pipe_chunking/stable/python/kubeless_chunking.py

Would maintainers of the repo be willing to consider this as an official solution?

**Comment by annalore** [comment]
My solution:
```
    with func_errors.labels(method).count_exceptions():
        with func_hist.labels(method).time():
            q = Queue()
            p = Process(target=funcWrap, args=(q, event, function_context))
            p.start()

            try:
                res = q.get(block=True, timeout=timeout)
            except queue.Empty:
                p.terminate()
                p.join()
                return bottle.HTTPError(408, "Timeout while processing the function")
            else:
                if isinstance(res, Exception):
                    raise res
                return res
```

**Comment by andresmgot** [comment]
Thanks @annalore! Since you found a working solution, would you mind creating a PR to fix it in the runtime?

**Comment by meseta** [comment]
We encountered this issue also, however not being able to return data bigger than 64kb was not an option for us, so we have implemented some chunking to allow more than 64kb of data to be returned.

My understanding is that python multiprocessing queues are pickling and serializing the object in order to send it over an OS pipe (see https://docs.python.org/3/library/multiprocessing.html#pipes-and-queues).  Our solution therefore is to pickle and serialize the return object ourselves, which allows us to send it through the queue in chunks smaller than the OS pipe max. We've added a `pipe_chunk_size` environmental variable which we've defaulted to 32kb, but could be lower if OS pipes are known to be smaller.

```python
def funcWrap(q, event, c):
    try:
        ret = func(event, c)
    except Exception as inst:
        ret = inst

    # chunk up return value to fit inside OS pipe max 64kb
    buff = io.BytesIO(pickle.dumps(ret))

    while True: # loop through and read chunks
        chunk = buff.read(pipe_chunk_size)
        q.put(chunk)
        if not chunk:
            break
```

However, there is some additional complexity in reading the data out, as the child process will not terminate until all buffered (queue put) items are flushed, as mentioned here: https://docs.python.org/3/library/multiprocessing.html#pipes-and-queues

> **Warning** As mentioned above, if a child process has put items on a queue (and it has not used JoinableQueue.cancel_join_thread), then that process will not terminate until all buffered items have been flushed to the pipe.
> 
> This means that if you try joining that process you may get a deadlock unless you are sure that all items which have been put on the queue have been consumed.

This means we cannot directly q.join() as it will deadlock. So instead, we have added our own polling with timeout that will continue to attempt to read data out of the queue while the thread is running; there is a small amount of polling overhead here while `func()` is running.

```python
    with func_errors.labels(method).count_exceptions():
        with func_hist.labels(method).time():
            q = Queue()
            p = Process(target=funcWrap, args=(q, event, function_context))
            p.start()

            acc = b"" # accumulate chunks
            end_time = time.time() + timeout # forecast timeout time
            finished = False

            while p.is_alive() or not q.empty():
                if time.time() > end_time: # timeout
                    break

                try:
                    res = q.get(timeout=max(chunk_min_wait, end_time-time.time()))
                except Empty:
                    pass
                else:
                    if not res:
                        finished = True
                        break

                    acc += res

            # If thread is still active
            if p.is_alive():
                p.terminate()
                p.join()

            if not finished:
                return bottle.HTTPError(408, "Timeout while processing the function")
            else:
                p.join()
                res = pickle.loads(acc)

                if isinstance(res, Exception):
                    raise res

                return res
```

The timeout handling ensures that whatever happens, it will break out of the loop after `timeout` seconds, and thus the existing timeout behaviour is maintained.  And the chunking should behave the same as the original code both the original code and the chunking code above use pickling; meaning it remains possible to send exceptions, dictionaries, and other objects through the pipe.

The full code can be seen here: https://github.com/HummingbirdTechGroup/runtimes/blob/pipe_chunking/stable/python/kubeless_chunking.py

If this method is acceptable as a solution, we're happy to raise a PR to the original kubeless.py

**Comment by andresmgot** [comment]
@annalore do you agree with this solution?

I am not an expert in Python so as far as this doesn't include a regression I am okay sending a PR for this.

**Comment by annalore** [comment]
@andresmgot @meseta I've added a PR here for my solution - https://github.com/kubeless/runtimes/pull/57/files

This is probably a cleaner solution to this problem.  We have had this running in a production system for a few months now with no issues.
